"""The Anthropic provider call: JSON extraction, retry classification, the debug capture on give-up, the
context-card threading and which model id a call uses (#72, #201, #268, #283, #434)."""
import io
import json
from contextlib import redirect_stdout

import anthropic
import httpx
import pytest
from _fakes import _ENGINE_REPLY, FakeClient, RaisingClient, full_slots, out, slot

from requivo.core.contracts import PRD, EngineOutput, Stories
from requivo.core.errors import ProviderOutputError
from requivo.core.persistence import load_model
from requivo.providers.anthropic import (
    AnthropicProvider,
    advise,
    answer_turn,
    current_model_name,
    derive_stories,
    generate_prd,
    run,
)
from requivo.providers.anthropic import completion as completion_module
from requivo.providers.anthropic.completion import _complete, _extract_json, _response_text
from requivo.providers.errors import EngineError
from requivo.render.markdown import prd_markdown
from requivo.render.terminal import render_stories
from requivo.usage import track_usage

_USER = [{"role": "user", "content": "leave approval"}]
_MODEL = out({"problem": slot(80, "explicit", "high")})
_BRIEF_REPLY = json.dumps({"complexity": "low", "solution": "S"})
_INCOMPLETE_REPLY = json.dumps({"model": {"problem": slot(80, "explicit", "high")},
                                "questions": [], "summary": {"objective": "o"}})


class _MaxTokensClient(FakeClient):
    """`FakeClient`, every reply flagged as cut off at the token ceiling."""

    def create(self, **kwargs):
        reply = super().create(**kwargs)
        reply.stop_reason = "max_tokens"
        return reply


def _complete_failing_with(exc) -> str:
    with pytest.raises(EngineError) as ei:
        _complete(RaisingClient(exc), "sys", _USER, EngineOutput)
    return str(ei.value)


# ── the reply's text, and the JSON in it ────────────────────────────────────────


@pytest.mark.parametrize("raw, expected", [
    ('```json\n{"a": 1}\n```', {"a": 1}), ('here it is: {"b": 2} — done', {"b": 2}), ("no json object anywhere", None),
])
def test_extract_json_strips_a_fence_slices_prose_and_refuses_garbage(raw, expected):
    if expected is None:
        with pytest.raises(ValueError):
            _extract_json(raw)
    else:
        assert _extract_json(raw) == expected


def test_response_text_concatenates_text_blocks_and_skips_others():
    class _Block:
        def __init__(self, type_, text=""):
            self.type, self.text = type_, text

    class _Resp:
        content = [_Block("thinking", "IGNORE"), _Block("text", "abc"), _Block("text", "def")]

    assert _response_text(_Resp()) == "abcdef"


# ── the discovery turn and the generators, against a canned client ──────────────


def test_run_returns_engine_output_and_wires_schema_and_context():
    fake = FakeClient(_ENGINE_REPLY)
    result = run(fake, _USER)
    assert isinstance(result, EngineOutput) and result.model["problem"].completeness == 80
    block = fake.calls[0]["system"][0]
    assert block["cache_control"] == {"type": "ephemeral"}
    assert "slots" in block["text"] and "## b2b-platform" in block["text"]  # {{SCHEMA}} and {{CONTEXT}}


def test_run_rejects_a_model_missing_required_slots(workspace):
    """A discovery reply missing a required slot is refused with a stable code, after every retry."""
    fake = FakeClient(_INCOMPLETE_REPLY, _INCOMPLETE_REPLY, _INCOMPLETE_REPLY)
    with pytest.raises(ProviderOutputError, match="missing required slots") as exc:
        run(fake, _USER)
    assert exc.value.to_dict()["code"] == "provider_output_invalid"
    assert exc.value.details["attempts"] == 3


def test_run_self_heals_when_a_retry_completes_the_model():
    fake = FakeClient(_INCOMPLETE_REPLY, _ENGINE_REPLY)
    assert run(fake, _USER).model["problem"].completeness == 80
    assert len(fake.calls) == 2
    assert "missing required slots" in fake.calls[1]["messages"][-1]["content"]  # the nudge names them


def test_generate_prd_from_saved_model_roundtrip(tmp_path):
    path = tmp_path / "model.json"
    path.write_text(_MODEL.model_dump_json(), encoding="utf-8")
    loaded = load_model(path)
    assert loaded.model["problem"].completeness == 80
    prd = generate_prd(FakeClient(json.dumps({"title": "Leave approval", "problem": "Approvals are lost in email."})), loaded)
    assert isinstance(prd, PRD) and prd.title == "Leave approval"
    md = prd_markdown(prd)
    assert md.startswith("# Leave approval") and "generated by Requivo" in md


def test_derive_stories_returns_structured_stories():
    stories = derive_stories(FakeClient(json.dumps({"stories": [{"id": "S1", "title": "Submit a leave request"}]})), _MODEL)
    assert isinstance(stories, Stories) and [s.id for s in stories.stories] == ["S1"]
    buf = io.StringIO()
    with redirect_stdout(buf):
        render_stories(stories)
    assert "=== USER STORIES ===" in buf.getvalue() and "[S1] Submit a leave request" in buf.getvalue()


@pytest.mark.parametrize("call, only, absent", [
    (lambda fake: run(fake, _USER, only=["b2b-platform"]), "b2b-platform", "financial-reporting"),
    (lambda fake: answer_turn(fake, _MODEL, "req", "answers", only=["event-ops"]), "event-ops", "financial-reporting"),
    (lambda fake: advise(fake, _MODEL, only=["financial-reporting"]), "financial-reporting", "b2b-platform"),
], ids=["run", "answer_turn", "generator"])
def test_the_context_card_selection_threads_through_every_call(call, only, absent):
    """`--context` reaches `load_context()` from the discovery, a refinement turn and a generator alike."""
    fake = FakeClient(_ENGINE_REPLY if only != "financial-reporting" else _BRIEF_REPLY)
    call(fake)
    system = fake.calls[0]["system"][0]["text"]
    assert f"## {only}" in system and f"## {absent}" not in system


# ── #201: which transport failures are worth retrying, and which are not ─────────


def _api_status(cls, status: int):
    request = httpx.Request("POST", "https://api.anthropic.com/v1/messages")
    return cls(message="boom", response=httpx.Response(status, request=request), body=None)


def test_complete_wraps_api_errors_as_a_clean_engine_error():
    assert "not modified" in _complete_failing_with(None)  # the reassurance that nothing was written


@pytest.mark.parametrize("cls, status", [(anthropic.AuthenticationError, 401), (anthropic.PermissionDeniedError, 403)])
def test_an_auth_failure_names_the_key_and_does_not_advise_retry(cls, status):
    """The remedy is the message's whole job; retrying a rejected credential never helps (#201)."""
    msg = _complete_failing_with(_api_status(cls, status))
    assert "ANTHROPIC_API_KEY" in msg and "requivo doctor" in msg and cls.__name__ in msg
    assert "Retry the command in a moment" not in msg and "not modified" in msg


def test_a_rate_limit_says_so_and_does_not_send_the_operator_straight_back():
    msg = _complete_failing_with(_api_status(anthropic.RateLimitError, 429))
    assert "rate-limited" in msg and "Wait for the limit to reset" in msg
    assert "ANTHROPIC_API_KEY" not in msg, "a rate limit is not a credential problem"


def test_a_connection_failure_keeps_the_wording_that_was_right_for_it():
    msg = _complete_failing_with(None)
    assert "Anthropic API unavailable" in msg and "Retry the command in a moment" in msg
    assert "ANTHROPIC_API_KEY" not in msg


def test_a_typeerror_out_of_the_sdk_is_not_a_traceback():
    """The belt against the SDK's own `TypeError` on an unresolvable auth method (#201)."""
    msg = _complete_failing_with(TypeError("Could not resolve authentication method."))
    assert "TypeError" in msg and "ANTHROPIC_API_KEY" in msg and "not modified" in msg


def test_complete_rejects_a_truncated_reply_that_fails_to_parse():
    with pytest.raises(EngineError, match="max_tokens"):
        _complete(_MaxTokensClient('{"model": {"problem":'), "sys", _USER, EngineOutput)


def test_complete_accepts_a_max_tokens_reply_whose_json_is_complete():
    """Parse-first: a reply flagged `max_tokens` whose JSON is nonetheless complete still succeeds."""
    complete = json.dumps({"model": full_slots(problem=slot(80, "explicit", "high")), "questions": [], "summary": {}})
    assert _complete(_MaxTokensClient(complete), "sys", _USER, EngineOutput).model["problem"].completeness == 80


# ── #283: the malformed reply survives retry give-up ──────────────────────────────


def test_a_retry_give_up_saves_the_final_raw_reply_and_names_it_in_the_error(workspace):
    bad_reply = '{"not": "an engine output"}'
    with pytest.raises(ProviderOutputError) as exc:
        run(FakeClient(bad_reply, bad_reply, bad_reply), _USER)
    saved = list((workspace / ".requivo" / "debug").glob("*.txt"))
    assert len(saved) == 1, "the give-up exit must write exactly one debug file"
    assert saved[0].read_text(encoding="utf-8") == bad_reply, "the exact final raw reply, byte for byte"
    assert str(saved[0]) in str(exc.value) and exc.value.details.get("raw_reply_path") == str(saved[0])


@pytest.mark.parametrize("client", [lambda: FakeClient(_ENGINE_REPLY), RaisingClient], ids=["success", "transport-failure"])
def test_only_a_retry_give_up_writes_a_debug_file(workspace, client):
    """A success has nothing to debug; a transport failure has no raw reply to save (#283)."""
    try:
        run(client(), _USER)
    except EngineError:
        pass
    assert not (workspace / ".requivo" / "debug").exists()


def test_a_prune_failure_does_not_discard_an_already_saved_reply(workspace, monkeypatch):
    """`_prune_debug_dir`'s `unlink` calls carried no exception handling of their own (#283 review)."""
    def _raise(root):
        raise PermissionError("locked by another process")

    monkeypatch.setattr(completion_module, "_prune_debug_dir", _raise)
    path = completion_module._save_failed_reply("some raw reply text", "EngineOutput")
    assert path is not None and path.read_text(encoding="utf-8") == "some raw reply text"


# ── #268: which model id a call uses, and #434: a constructor-level override ─────


def test_current_model_name_reads_env_override(monkeypatch):
    monkeypatch.delenv("REQUIVO_MODEL", raising=False)
    monkeypatch.delenv("MODEL", raising=False)
    assert current_model_name() == "claude-sonnet-5"


def test_current_model_name_prefers_requivo_model_over_the_default(monkeypatch):
    monkeypatch.delenv("MODEL", raising=False)
    monkeypatch.setenv("REQUIVO_MODEL", "claude-opus-4-8")
    assert current_model_name() == "claude-opus-4-8"


def test_current_model_name_falls_back_to_bare_model(monkeypatch):
    """The bare `MODEL` name predates `REQUIVO_MODEL` and existing setups keep working (#268)."""
    monkeypatch.delenv("REQUIVO_MODEL", raising=False)
    monkeypatch.setenv("MODEL", "claude-opus-4-8")
    assert current_model_name() == "claude-opus-4-8"


def test_current_model_name_prefers_requivo_model_when_both_are_set(monkeypatch):
    """A shell exporting a generic `MODEL` for another tool must not steer Requivo once `REQUIVO_MODEL` is set (#268)."""
    monkeypatch.setenv("MODEL", "some-other-tools-model")
    monkeypatch.setenv("REQUIVO_MODEL", "claude-opus-4-8")
    assert current_model_name() == "claude-opus-4-8"


def test_two_constructed_providers_record_and_price_independently(monkeypatch):
    """Two `AnthropicProvider`s in one process, each billed at its own model's rate (#434)."""
    monkeypatch.setenv("REQUIVO_MODEL", "claude-opus-4-8")  # ambient value neither provider should use
    sonnet = AnthropicProvider(FakeClient(_ENGINE_REPLY), model="claude-sonnet-5")
    haiku = AnthropicProvider(FakeClient(_ENGINE_REPLY), model="claude-haiku-4-5")
    with track_usage() as ledger:
        sonnet.analyze("leave approval")
        haiku.analyze("leave approval")
    assert [c.model for c in ledger.calls] == ["claude-sonnet-5", "claude-haiku-4-5"]
    sonnet_rate, haiku_rate = ledger.calls[0].rate_per_mtok, ledger.calls[1].rate_per_mtok
    assert sonnet_rate is not None and haiku_rate is not None and sonnet_rate != haiku_rate


def test_a_constructed_model_makes_no_env_read(monkeypatch):
    """A constructed id wins over the ambient `REQUIVO_MODEL`; default construction still reads it (#434)."""
    monkeypatch.setenv("REQUIVO_MODEL", "claude-opus-4-8")
    constructed = AnthropicProvider(FakeClient(_ENGINE_REPLY), model="claude-haiku-4-5")
    constructed.analyze("leave approval")
    assert constructed.client.calls[0]["model"] == "claude-haiku-4-5" == constructed.model_name()
    ambient = AnthropicProvider(FakeClient(_ENGINE_REPLY))  # MUST FIRE: the positive control
    ambient.analyze("leave approval")
    assert ambient.client.calls[0]["model"] == "claude-opus-4-8" == ambient.model_name()


def test_default_construction_is_byte_identical_to_before_434(monkeypatch):
    monkeypatch.setenv("REQUIVO_MODEL", "claude-haiku-4-5")
    fake = FakeClient(_ENGINE_REPLY)
    provider = AnthropicProvider(fake)
    provider.analyze("leave approval")
    assert fake.calls[0]["model"] == current_model_name() == "claude-haiku-4-5" == provider.model_name()


def test_generate_threads_the_constructed_model_too():
    fake = FakeClient(_BRIEF_REPLY)
    AnthropicProvider(fake, model="claude-haiku-4-5").generate("brief", _MODEL)
    assert fake.calls[0]["model"] == "claude-haiku-4-5"
