from __future__ import annotations

from requivo.core.analysis import readiness_blockers, slot_label, slot_meta
from requivo.core.contracts import (
    PRD,
    AcceptanceCriteria,
    Brief,
    Confidence,
    EngineOutput,
    EnvelopeElement,
    EnvelopeOrigin,
    Epic,
    EstimateDraft,
    GoToMarketPlan,
    ReleaseNotes,
    ScenarioKind,
    Stories,
)
from requivo.core.perimeters import DEFAULT_PERIMETER, GO_TO_MARKET

_KIND_TAG = {
    ScenarioKind.happy_path: "Happy path",
    ScenarioKind.edge_case: "Edge case",
    ScenarioKind.error: "Error",
    ScenarioKind.permission: "Permission",
}


def _cell(text: str) -> str:
    """Make text safe for a table cell: escape a literal `|`, flatten a newline."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _line(text: str) -> str:
    """Keep provider free text on one line: a newline inside a title would open a second heading when
    `markdown_to_html` re-parses the line. `test_a_newline_inside_a_provider_field_cannot_open_a_new_heading`."""
    return " ".join(text.split())


def _stated(out: EngineOutput, confidence: Confidence, perimeter: str = DEFAULT_PERIMETER) -> list[str]:
    """The topics carrying a stated value at a given provenance, in schema order, as `**Label** —
    value`: read off the model, never restated by the provider (Voice rule). `perimeter` (#609)
    selects the labels."""
    order = slot_meta(perimeter)[1]
    return [f"- **{slot_label(sid, perimeter)}** — {out.model[sid].value.strip()}"
            for sid in order
            if sid in out.model and out.model[sid].confidence is confidence
            and out.model[sid].value.strip()]


def _excluded(out: EngineOutput, perimeter: str = DEFAULT_PERIMETER) -> list[str]:
    """Excluded options projected off the model (#599), by label (Voice rule), `_line()`-flattened."""
    lines = []
    for ex in out.exclusions:
        line = f"- **{_line(ex.option)}** — {_line(ex.reason)}"
        if ex.rests_on:
            line += f" _(rests on: {', '.join(slot_label(sid, perimeter) for sid in ex.rests_on)})_"
        lines.append(line)
    return lines


def _thresholds(out: EngineOutput, perimeter: str = DEFAULT_PERIMETER) -> list[str]:
    """Decision thresholds projected off the model (#604), by label, `_line()`-flattened."""
    lines = []
    for th in out.thresholds:
        line = f"- **{_line(th.condition)}** → {_line(th.action)}"
        if th.rests_on:
            line += f" _(rests on: {', '.join(slot_label(sid, perimeter) for sid in th.rests_on)})_"
        lines.append(line)
    return lines


def brief_markdown(out: EngineOutput, brief: Brief) -> str:
    """Render the decision brief: what is settled and what is assumed first, then the judgment.
    Half of it is deterministic: the confirmed, assumed, excluded, threshold and blocking sections are
    projected off the model, because a restatement can drift and a projection cannot. No slot ids or
    confidence labels in either half (Voice rule)."""
    blockers = [slot_label(sid) for sid in readiness_blockers(out)]
    draft = " — Draft: unresolved topics remain" if blockers else ""
    md: list[str] = [f"# Decision Brief{draft}", "",
                     "> What to review before committing to the scope — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            md.extend([f"## {heading}", "", *lines, ""])

    summary = []
    if out.summary.objective:
        summary.append(f"**Objective:** {out.summary.objective}")
    if brief.problem:
        summary.append(f"**Problem:** {brief.problem}")
    if brief.solution:
        summary.append(f"**Solution:** {brief.solution}")
    summary.append(f"**Complexity:** {brief.complexity.value}"
                   + (f" — {'; '.join(brief.complexity_reasons)}" if brief.complexity_reasons else ""))
    if brief.cost_driver:
        summary.append(f"**Main cost driver:** {brief.cost_driver}")
    section("Request and objective", summary)

    section("Current understanding", [out.summary.scope] if out.summary.scope else [])
    section("What is confirmed", _stated(out, Confidence.explicit))

    assumed = _stated(out, Confidence.inferred)
    if out.summary.assumptions:
        assumed += [f"- {a}" for a in out.summary.assumptions]
    if assumed:
        assumed = [*assumed, "",
                   "_Each of these was inferred, not stated. Confirm the ones that would change the "
                   "build._"]
    section("Important assumptions", assumed)

    # `_line()`-flattened, or a newline in a provider decision opens a forged heading (#599).
    decisions: list[str] = []
    for d in brief.decisions:
        line = f"- **{_line(d.decision)}**"
        if d.why:
            line += f" — {_line(d.why)}"
        decisions.append(line)
        if d.alternative:
            decisions.append(f"  - _Alternative weighed:_ {_line(d.alternative)}")
        if d.tradeoff:
            decisions.append(f"  - _Trade-off accepted:_ {_line(d.tradeoff)}")
    section("Decisions made", decisions)

    section("Scope implications", [f"- {i}" for i in brief.introduces])

    section("Out of scope", _excluded(out))

    section("Decision thresholds", _thresholds(out))

    challenges: list[str] = []
    for c in brief.challenges:
        challenges += [f"### {_line(c.headline)}",
                       f"- **Premise:** {_line(c.premise)}",
                       f"- **Alternative:** {_line(c.alternative)}",
                       f"- **Consequence:** {_line(c.consequence)}",
                       f"- **Recommendation:** {_line(c.recommendation)}", ""]
    section("Assumptions worth contesting", challenges)

    section("Main risks", [f"- {r}" for r in brief.risks])

    open_items = [f"- {d}" for d in brief.open_decisions]
    if blockers:
        open_items.append(f"- Unresolved and blocking: {' · '.join(blockers)}")
    if out.summary.blind_spot:
        open_items.append(f"- Least explored: {out.summary.blind_spot}")
    section("Unresolved questions", open_items)

    section("Opportunities", [
        f"- **{_line(o.text)}** (leverage: {o.leverage.value})"
        + (f" — reaches {', '.join(o.modules)}" if o.modules else "")
        for o in brief.opportunities])

    # Not a second readiness question (#165): `test_every_surface_asks_the_same_readiness_question`.
    section("Are we ready?",
            [f"**Not ready.** This brief is a draft: these topics are still unconfirmed and can move "
             f"the solution — {' · '.join(blockers)}." if blockers
             else "**Ready.** No high-impact topic is still unresolved."])
    section("Recommended next steps", [f"- {s}" for s in brief.next_steps])

    return "\n".join(md).rstrip() + "\n"


def gtm_plan_markdown(out: EngineOutput, brief: GoToMarketPlan) -> str:
    """Render the go-to-market perimeter's one artifact (#609): `brief_markdown`'s split, over its own
    twelve slots, every projection called with `GO_TO_MARKET` explicitly."""
    blockers = [slot_label(sid, GO_TO_MARKET) for sid in readiness_blockers(out, GO_TO_MARKET)]
    draft = " — Draft: unresolved topics remain" if blockers else ""
    md: list[str] = [f"# Go-to-Market Plan{draft}", "",
                     "> What to review before committing to this push — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            md.extend([f"## {heading}", "", *lines, ""])

    summary = []
    if out.summary.objective:
        summary.append(f"**Objective:** {out.summary.objective}")
    section("Objective", summary)

    section("Current understanding", [out.summary.scope] if out.summary.scope else [])
    section("What is confirmed", _stated(out, Confidence.explicit, GO_TO_MARKET))

    assumed = _stated(out, Confidence.inferred, GO_TO_MARKET)
    if out.summary.assumptions:
        assumed += [f"- {a}" for a in out.summary.assumptions]
    if assumed:
        assumed = [*assumed, "",
                   "_Each of these was inferred, not stated. Confirm the ones that would change the "
                   "plan._"]
    section("Important assumptions", assumed)

    section("Resource envelope", _envelope_lines(brief.envelope, GO_TO_MARKET))

    plan: list[str] = [f"- {_line(p)}" for p in brief.plan]
    if brief.rationale:
        plan += ["", _line(brief.rationale)]
    section("The plan", plan)

    section("Out of scope", _excluded(out, GO_TO_MARKET))
    section("Decision thresholds", _thresholds(out, GO_TO_MARKET))
    section("Main risks", [f"- {r}" for r in brief.risks])

    open_items = [f"- {d}" for d in brief.open_decisions]
    if blockers:
        open_items.append(f"- Unresolved and blocking: {' · '.join(blockers)}")
    if out.summary.blind_spot:
        open_items.append(f"- Least explored: {out.summary.blind_spot}")
    section("Unresolved questions", open_items)

    # Not a second readiness question, as in `brief_markdown`.
    section("Are we ready?",
            [f"**Not ready.** This plan is a draft: these topics are still unconfirmed and can move "
             f"it — {' · '.join(blockers)}." if blockers
             else "**Ready.** No high-impact topic is still unresolved."])

    return "\n".join(md).rstrip() + "\n"


def _envelope_lines(elements: list[EnvelopeElement], perimeter: str = DEFAULT_PERIMETER) -> list[str]:
    """Render the resource envelope an artifact was planned within (#603): a slot-sourced element by
    its label, an assumed one said plainly. `perimeter` (#609) selects the labels."""
    lines = []
    for e in elements:
        # The enum decides, never the field's presence (#603).
        slot = e.source_slot if e.origin is EnvelopeOrigin.slot else None
        origin = f"stated in {slot_label(slot, perimeter)}" if slot else "assumption — not stated in the model"
        lines.append(f"- **{_line(e.kind)}** — {_line(e.value)} _({origin})_")
    return lines


def prd_markdown(prd: PRD) -> str:
    """Render a PRD as a clean, shareable Markdown document."""
    out: list[str] = [f"# {prd.title}", "", "> Product Requirements Document — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            out.extend([f"## {heading}", "", *lines, ""])

    def bullets(items: list[str]) -> list[str]:
        return [f"- {i}" for i in items]

    if prd.summary:
        section("Summary", [prd.summary])
    if prd.problem:
        section("Problem", [prd.problem])
    section("Resource envelope", _envelope_lines(prd.envelope))
    section("Goals", bullets(prd.goals))
    section("Users & roles", bullets(prd.users))

    scope: list[str] = []
    if prd.in_scope:
        scope += ["**In scope**", "", *bullets(prd.in_scope), ""]
    if prd.out_of_scope:
        scope += ["**Out of scope**", "", *bullets(prd.out_of_scope)]
    section("Scope", scope)

    if prd.requirements:
        rows = ["| ID | Requirement | Priority |", "|----|-------------|----------|"]
        rows += [f"| {_cell(r.id)} | {_cell(r.requirement)} | {r.priority.value.capitalize()} |"
                 for r in prd.requirements]
        section("Functional requirements", rows)

    section("Workflow", [f"{i}. {step}" for i, step in enumerate(prd.workflow, 1)])
    section("Business rules", bullets(prd.business_rules))
    section("Permissions", bullets(prd.permissions))
    section("Integrations & notifications", bullets(prd.integrations))
    section("Edge cases", bullets(prd.edge_cases))
    section("Acceptance criteria", [f"- [ ] {a}" for a in prd.acceptance_criteria])
    section("Assumptions", bullets(prd.assumptions))
    section("Open questions", bullets(prd.open_questions))
    section("Risks", bullets(prd.risks))

    return "\n".join(out).rstrip() + "\n"


def stories_markdown(s: Stories) -> str:
    """Render user stories as Markdown, one section per story; saveable since #519
    (`decision: the-estimate-graduates`). `Story.slots` are shown by label (Voice rule)."""
    out: list[str] = ["# User stories", "", "> User stories — generated by Requivo", ""]

    for st in s.stories:
        out += [f"## {_line(st.id)} — {_line(st.title)}", ""]
        if st.as_a or st.i_want or st.so_that:
            out += [f"As a {_line(st.as_a)}, I want {_line(st.i_want)}, so that {_line(st.so_that)}.",
                    ""]
        if st.acceptance:
            out += ["**Acceptance**", "", *[f"- [ ] {_line(a)}" for a in st.acceptance], ""]
        if st.slots:
            out += [f"_Traces to: {', '.join(slot_label(sid) for sid in st.slots)}_", ""]

    return "\n".join(out).rstrip() + "\n"


def estimate_markdown(draft: EstimateDraft, soft: list[str], confidence: str) -> str:
    """Render the uncertainty-aware estimate as Markdown from the provider's draft and the two facts
    computed in core (soft slots, confidence); totals are summed here. Saveable since #519
    (`decision: the-estimate-graduates`). The spread section is never silently absent."""
    total_low = sum(i.days_low for i in draft.items)
    total_high = sum(i.days_high for i in draft.items)
    out: list[str] = ["# Estimate", "", "> Uncertainty-aware estimate — generated by Requivo", "",
                      f"**Total:** {total_low:g}–{total_high:g} days across {len(draft.items)} "
                      f"stor{'y' if len(draft.items) == 1 else 'ies'} · **Confidence:** {confidence}",
                      ""]

    if draft.items:
        rows = ["| Story | Complexity | Days | Drives |", "|---|---|---|---|"]
        rows += [f"| {_cell(i.story_id)} — {_cell(i.title)} | {i.complexity.value} "
                 f"| {i.days_low:g}–{i.days_high:g} "
                 f"| {_cell(', '.join(slot_label(d) for d in i.drives))} |"
                 for i in draft.items]
        out += ["## Per story", "", *rows, ""]

    notes = [f"- **{_line(i.title)}** — {_line(i.note)}" for i in draft.items if i.note]
    if notes:
        out += ["## Notes", "", *notes, ""]

    if soft:
        out += ["## Spread driven by unresolved topics", "",
                *[f"- {slot_label(sid)}" for sid in soft], ""]
    else:
        out += ["No unresolved topic widens these ranges.", ""]

    if draft.risks:
        out += ["## Risks and unknowns", "", *[f"- {_line(r)}" for r in draft.risks], ""]

    return "\n".join(out).rstrip() + "\n"


def criteria_markdown(ac: AcceptanceCriteria) -> str:
    """Render acceptance criteria as a Given/When/Then Markdown checklist for recette."""
    out: list[str] = [f"# {ac.title}", "", "> Acceptance criteria — generated by Requivo", ""]

    for feature in ac.features:
        out += [f"## {feature.name}", ""]
        for s in feature.scenarios:
            out.append(f"### [ ] {s.id} — {s.title}  _{_KIND_TAG.get(s.kind, s.kind.value)}_")
            out.append("")
            for i, g in enumerate(s.given):
                out.append(f"- **{'Given' if i == 0 else 'And'}** {g}")
            if s.when:
                out.append(f"- **When** {s.when}")
            for i, t in enumerate(s.then):
                out.append(f"- **{'Then' if i == 0 else 'And'}** {t}")
            out.append("")

    if ac.open_questions:
        out += ["## Open questions", "", *[f"- {q}" for q in ac.open_questions], ""]

    return "\n".join(out).rstrip() + "\n"


def epic_markdown(epic: Epic) -> str:
    """Render a delivery epic as Markdown: goal, scope, then a checklist of trackable issues."""
    out: list[str] = [f"# Epic: {epic.title}", "", "> Delivery epic — generated by Requivo", ""]
    if epic.milestone:
        out += [f"**Milestone:** {epic.milestone}", ""]
    if epic.goal:
        out += [f"**Goal:** {epic.goal}", ""]
    if epic.business_value:
        out += [f"**Business value:** {epic.business_value}", ""]

    if epic.in_scope:
        out += ["## In scope", "", *[f"- {i}" for i in epic.in_scope], ""]
    if epic.out_of_scope:
        out += ["## Out of scope", "", *[f"- {i}" for i in epic.out_of_scope], ""]

    if epic.issues:
        out += ["## Issues", ""]
        for issue in epic.issues:
            out.append(f"### [ ] {issue.id} — {issue.title}")
            out.append("")
            meta: list[str] = []
            if issue.labels:
                meta.append("**Labels:** " + ", ".join(f"`{lab}`" for lab in issue.labels))
            if issue.depends_on:
                meta.append("**Depends on:** " + ", ".join(issue.depends_on))
            if meta:
                out += [" · ".join(meta), ""]
            if issue.description:
                out += [issue.description, ""]

    if epic.open_questions:
        out += ["## Open questions", "", *[f"- {q}" for q in epic.open_questions], ""]

    return "\n".join(out).rstrip() + "\n"


def release_markdown(rn: ReleaseNotes) -> str:
    """Render client-facing release notes as a clean, shareable Markdown announcement."""
    heading = f"# {rn.title}" + (f" — {rn.version}" if rn.version else "")
    out: list[str] = [heading, "", "> Release notes — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            out.extend([f"## {heading}", "", *lines, ""])

    if rn.summary:
        out += [rn.summary, ""]
    section("What's new", [f"- {h}" for h in rn.highlights])
    section("Not included yet", [f"- {lim}" for lim in rn.known_limitations])
    section("Before you start", [f"- {n}" for n in rn.notes])

    return "\n".join(out).rstrip() + "\n"
