from __future__ import annotations

from requivo.core.analysis import readiness_blockers, slot_label, slot_meta
from requivo.core.contracts import (
    PRD,
    AcceptanceCriteria,
    Brief,
    Confidence,
    EngineOutput,
    Epic,
    EstimateDraft,
    ReleaseNotes,
    ScenarioKind,
    Stories,
)

_KIND_TAG = {
    ScenarioKind.happy_path: "Happy path",
    ScenarioKind.edge_case: "Edge case",
    ScenarioKind.error: "Error",
    ScenarioKind.permission: "Permission",
}


def _cell(text: str) -> str:
    """Make text safe for a Markdown table cell: a literal `|` closes the cell and a newline ends the
    row, so a requirement containing either would break the table. Escape one, flatten the other."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _stated(out: EngineOutput, confidence: Confidence) -> list[str]:
    """The topics carrying a stated value at a given provenance, in schema order, as `**Label** — value`.

    This separates what the client actually said from what the engine filled in on their behalf — the
    single most useful distinction a scope review can be handed, and one nobody has to take on trust,
    because it is read off the model rather than written by the provider. The Voice rule holds: the
    label is the human one and the numbers behind it never appear."""
    order = slot_meta()[1]
    return [f"- **{slot_label(sid)}** — {out.model[sid].value.strip()}"
            for sid in order
            if sid in out.model and out.model[sid].confidence is confidence
            and out.model[sid].value.strip()]


def brief_markdown(out: EngineOutput, brief: Brief) -> str:
    """Render the decision brief — the document a scope review is run from.

    It answers one question: *what would I need to review with a client, a product lead or an
    engineering lead before estimating this?* So it opens with what is settled and what is merely
    assumed, and only then gives the judgment (decisions, contested premises, complexity, risks,
    opportunities). It is deliberately not a PRD; `prd_markdown` is.

    Half of it is deterministic. What is confirmed, what is being assumed and what still blocks are
    read straight off the model — the provider is never asked to restate facts it was given, because a
    restatement can drift from the model while a projection cannot. The prose sections are the ones
    that need judgment. Slot ids and internal signals (completeness, confidence labels) never appear
    in either half, matching the Voice rule the LLM prose already follows."""
    blockers = [slot_label(sid) for sid in readiness_blockers(out)]
    draft = " — Draft: unresolved topics remain" if blockers else ""
    md: list[str] = [f"# Decision Brief{draft}", "",
                     "> What to review before committing to the scope — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            md.extend([f"## {heading}", "", *lines, ""])

    summary = []
    if out.summary.objective:
        summary.append(f"**Objective:** {out.summary.objective}")
    if brief.problem:
        summary.append(f"**Problem:** {brief.problem}")
    if brief.solution:
        summary.append(f"**Solution:** {brief.solution}")
    summary.append(f"**Complexity:** {brief.complexity.value}"
                   + (f" — {'; '.join(brief.complexity_reasons)}" if brief.complexity_reasons else ""))
    if brief.cost_driver:
        summary.append(f"**Main cost driver:** {brief.cost_driver}")
    section("Request and objective", summary)

    section("Current understanding", [out.summary.scope] if out.summary.scope else [])
    section("What is confirmed", _stated(out, Confidence.explicit))

    assumed = _stated(out, Confidence.inferred)
    if out.summary.assumptions:
        assumed += [f"- {a}" for a in out.summary.assumptions]
    if assumed:
        assumed = [*assumed, "",
                   "_Each of these was inferred, not stated. Confirm the ones that would change the "
                   "build._"]
    section("Important assumptions", assumed)

    decisions: list[str] = []
    for d in brief.decisions:
        line = f"- **{d.decision}**"
        if d.why:
            line += f" — {d.why}"
        decisions.append(line)
        if d.alternative:
            decisions.append(f"  - _Alternative weighed:_ {d.alternative}")
        if d.tradeoff:
            decisions.append(f"  - _Trade-off accepted:_ {d.tradeoff}")
    section("Decisions made", decisions)

    section("Scope implications", [f"- {i}" for i in brief.introduces])

    challenges: list[str] = []
    for c in brief.challenges:
        challenges += [f"### {c.headline}",
                       f"- **Premise:** {c.premise}",
                       f"- **Alternative:** {c.alternative}",
                       f"- **Consequence:** {c.consequence}",
                       f"- **Recommendation:** {c.recommendation}", ""]
    section("Assumptions worth contesting", challenges)

    section("Main risks", [f"- {r}" for r in brief.risks])

    open_items = [f"- {d}" for d in brief.open_decisions]
    if blockers:
        open_items.append(f"- Unresolved and blocking: {' · '.join(blockers)}")
    if out.summary.blind_spot:
        open_items.append(f"- Least explored: {out.summary.blind_spot}")
    section("Unresolved questions", open_items)

    section("Opportunities", [
        f"- **{o.text}** (leverage: {o.leverage.value})"
        + (f" — reaches {', '.join(o.modules)}" if o.modules else "")
        for o in brief.opportunities])

    # Not a second readiness question. `Ready to estimate?` read as a threshold of its own while
    # branching on the same blocker list as everywhere else, and asking *ready for a first decision
    # brief* here would be circular — the reader is holding one. So the one boolean is stated as what
    # it means for this document (#165). Pinned by
    # `test_every_surface_asks_the_same_readiness_question`.
    section("Are we ready?",
            [f"**Not ready.** This brief is a draft: these topics are still unconfirmed and can move "
             f"the solution — {' · '.join(blockers)}." if blockers
             else "**Ready.** No high-impact topic is still unresolved."])
    section("Recommended next steps", [f"- {s}" for s in brief.next_steps])

    return "\n".join(md).rstrip() + "\n"


def prd_markdown(prd: PRD) -> str:
    """Render a PRD as a clean, shareable Markdown document."""
    out: list[str] = [f"# {prd.title}", "", "> Product Requirements Document — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            out.extend([f"## {heading}", "", *lines, ""])

    def bullets(items: list[str]) -> list[str]:
        return [f"- {i}" for i in items]

    if prd.summary:
        section("Summary", [prd.summary])
    if prd.problem:
        section("Problem", [prd.problem])
    section("Goals", bullets(prd.goals))
    section("Users & roles", bullets(prd.users))

    scope: list[str] = []
    if prd.in_scope:
        scope += ["**In scope**", "", *bullets(prd.in_scope), ""]
    if prd.out_of_scope:
        scope += ["**Out of scope**", "", *bullets(prd.out_of_scope)]
    section("Scope", scope)

    if prd.requirements:
        rows = ["| ID | Requirement | Priority |", "|----|-------------|----------|"]
        rows += [f"| {_cell(r.id)} | {_cell(r.requirement)} | {r.priority.value.capitalize()} |"
                 for r in prd.requirements]
        section("Functional requirements", rows)

    section("Workflow", [f"{i}. {step}" for i, step in enumerate(prd.workflow, 1)])
    section("Business rules", bullets(prd.business_rules))
    section("Permissions", bullets(prd.permissions))
    section("Integrations & notifications", bullets(prd.integrations))
    section("Edge cases", bullets(prd.edge_cases))
    section("Acceptance criteria", [f"- [ ] {a}" for a in prd.acceptance_criteria])
    section("Assumptions", bullets(prd.assumptions))
    section("Open questions", bullets(prd.open_questions))
    section("Risks", bullets(prd.risks))

    return "\n".join(out).rstrip() + "\n"


def stories_markdown(s: Stories) -> str:
    """Render user stories as a shareable Markdown document — one section per story, its acceptance
    as a checklist, and the topics it traces to by their human labels.

    Saveable since #519 (`decision: the-estimate-graduates`): the estimate is reasoned against these
    stories, so the file beside `estimate.md` is the half of its basis that used to go unrecorded.
    The Voice rule holds — `Story.slots` are ids the contract validates against the schema, and a
    reader sees their labels, never the ids."""
    out: list[str] = ["# User stories", "", "> User stories — generated by Requivo", ""]

    for st in s.stories:
        out += [f"## {st.id} — {st.title}", ""]
        if st.as_a or st.i_want or st.so_that:
            out += [f"As a {st.as_a}, I want {st.i_want}, so that {st.so_that}.", ""]
        if st.acceptance:
            out += ["**Acceptance**", "", *[f"- [ ] {a}" for a in st.acceptance], ""]
        if st.slots:
            out += [f"_Traces to: {', '.join(slot_label(sid) for sid in st.slots)}_", ""]

    return "\n".join(out).rstrip() + "\n"


def estimate_markdown(draft: EstimateDraft, soft: list[str], confidence: str) -> str:
    """Render the uncertainty-aware estimate as a shareable Markdown document.

    The same three inputs `render_estimate` prints, because they are the estimate: the provider's
    draft, and the two facts computed in core from the same model — the soft slots that widen the
    ranges and the confidence derived from how many there are. Totals are summed here, both ends,
    so the document cannot carry a total the items do not add up to.

    Saveable since #519 (`decision: the-estimate-graduates`) — the one artifact where being stale
    costs money, and the file is what lets the dependency graph flag it. The Voice rule holds: the
    soft slots and each item's `drives` are ids, and the reader sees labels. The spread section is
    never silently absent — a solid model gets a sentence saying so, because an absent heading reads
    the same as a rendering that forgot it."""
    total_low = sum(i.days_low for i in draft.items)
    total_high = sum(i.days_high for i in draft.items)
    out: list[str] = ["# Estimate", "", "> Uncertainty-aware estimate — generated by Requivo", "",
                      f"**Total:** {total_low:g}–{total_high:g} days across {len(draft.items)} "
                      f"stor{'y' if len(draft.items) == 1 else 'ies'} · **Confidence:** {confidence}",
                      ""]

    if draft.items:
        rows = ["| Story | Complexity | Days | Drives |", "|---|---|---|---|"]
        rows += [f"| {_cell(i.story_id)} — {_cell(i.title)} | {i.complexity.value} "
                 f"| {i.days_low:g}–{i.days_high:g} "
                 f"| {_cell(', '.join(slot_label(d) for d in i.drives))} |"
                 for i in draft.items]
        out += ["## Per story", "", *rows, ""]

    notes = [f"- **{i.title}** — {i.note}" for i in draft.items if i.note]
    if notes:
        out += ["## Notes", "", *notes, ""]

    if soft:
        out += ["## Spread driven by unresolved topics", "",
                *[f"- {slot_label(sid)}" for sid in soft], ""]
    else:
        out += ["No unresolved topic widens these ranges.", ""]

    if draft.risks:
        out += ["## Risks and unknowns", "", *[f"- {r}" for r in draft.risks], ""]

    return "\n".join(out).rstrip() + "\n"


def criteria_markdown(ac: AcceptanceCriteria) -> str:
    """Render acceptance criteria as a Given/When/Then Markdown checklist for recette."""
    out: list[str] = [f"# {ac.title}", "", "> Acceptance criteria — generated by Requivo", ""]

    for feature in ac.features:
        out += [f"## {feature.name}", ""]
        for s in feature.scenarios:
            out.append(f"### [ ] {s.id} — {s.title}  _{_KIND_TAG.get(s.kind, s.kind.value)}_")
            out.append("")
            for i, g in enumerate(s.given):
                out.append(f"- **{'Given' if i == 0 else 'And'}** {g}")
            if s.when:
                out.append(f"- **When** {s.when}")
            for i, t in enumerate(s.then):
                out.append(f"- **{'Then' if i == 0 else 'And'}** {t}")
            out.append("")

    if ac.open_questions:
        out += ["## Open questions", "", *[f"- {q}" for q in ac.open_questions], ""]

    return "\n".join(out).rstrip() + "\n"


def epic_markdown(epic: Epic) -> str:
    """Render a delivery epic as Markdown: goal, scope, then a checklist of trackable issues."""
    out: list[str] = [f"# Epic: {epic.title}", "", "> Delivery epic — generated by Requivo", ""]
    if epic.milestone:
        out += [f"**Milestone:** {epic.milestone}", ""]
    if epic.goal:
        out += [f"**Goal:** {epic.goal}", ""]
    if epic.business_value:
        out += [f"**Business value:** {epic.business_value}", ""]

    if epic.in_scope:
        out += ["## In scope", "", *[f"- {i}" for i in epic.in_scope], ""]
    if epic.out_of_scope:
        out += ["## Out of scope", "", *[f"- {i}" for i in epic.out_of_scope], ""]

    if epic.issues:
        out += ["## Issues", ""]
        for issue in epic.issues:
            out.append(f"### [ ] {issue.id} — {issue.title}")
            out.append("")
            meta: list[str] = []
            if issue.labels:
                meta.append("**Labels:** " + ", ".join(f"`{lab}`" for lab in issue.labels))
            if issue.depends_on:
                meta.append("**Depends on:** " + ", ".join(issue.depends_on))
            if meta:
                out += [" · ".join(meta), ""]
            if issue.description:
                out += [issue.description, ""]

    if epic.open_questions:
        out += ["## Open questions", "", *[f"- {q}" for q in epic.open_questions], ""]

    return "\n".join(out).rstrip() + "\n"


def release_markdown(rn: ReleaseNotes) -> str:
    """Render client-facing release notes as a clean, shareable Markdown announcement."""
    heading = f"# {rn.title}" + (f" — {rn.version}" if rn.version else "")
    out: list[str] = [heading, "", "> Release notes — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            out.extend([f"## {heading}", "", *lines, ""])

    if rn.summary:
        out += [rn.summary, ""]
    section("What's new", [f"- {h}" for h in rn.highlights])
    section("Not included yet", [f"- {lim}" for lim in rn.known_limitations])
    section("Before you start", [f"- {n}" for n in rn.notes])

    return "\n".join(out).rstrip() + "\n"
